GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][5]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][5]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[4][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[4][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, {PropagatorEndpoints -> Vertex}}\
    , {Vertex[3][1] -> {7, 10}, Vertex[4][5] -> {13, 10}, 
    Vertex[1][3] -> {20, 15}, Vertex[1][4] -> {20, 10}, 
    Vertex[1][5] -> {20, 5}, Vertex[1][1] -> {0, 15}, Vertex[1][2] -> {0, 5}}\
    , {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][5]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][5]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[4][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[4][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, {PropagatorEndpoints -> Vertex}}\
    , {Vertex[4][5] -> {10, 7}, Vertex[1][3] -> {20, 15}, 
    Vertex[1][4] -> {20, 10}, Vertex[1][5] -> {20, 5}, 
    Vertex[1][1] -> {0, 15}, Vertex[1][2] -> {0, 5}, 
    Vertex[3][1] -> {10, 15}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][5]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][5]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[4][5]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, {PropagatorEndpoints -> Vertex}}\
    , {Vertex[4][5] -> {10, 7}, Vertex[1][3] -> {20, 15}, 
    Vertex[1][4] -> {20, 10}, Vertex[1][5] -> {20, 5}, 
    Vertex[1][1] -> {0, 15}, Vertex[1][2] -> {0, 5}, 
    Vertex[3][4] -> {10, 15}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][5]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][5], Vertex[4][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, {PropagatorEndpoints -> Vertex}}\
    , {Vertex[4][4] -> {10, 7}, Vertex[1][3] -> {20, 15}, 
    Vertex[1][4] -> {20, 10}, Vertex[1][5] -> {20, 5}, 
    Vertex[1][1] -> {0, 15}, Vertex[1][2] -> {0, 5}, 
    Vertex[3][5] -> {10, 15}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][5]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][5], Vertex[4][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, {PropagatorEndpoints -> Vertex}}\
    , {Vertex[1][3] -> {20, 15}, Vertex[1][4] -> {20, 10}, 
    Vertex[1][5] -> {20, 5}, Vertex[1][1] -> {0, 15}, 
    Vertex[1][2] -> {0, 5}, Vertex[4][4] -> {10, 13}, 
    Vertex[3][5] -> {10, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][5]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][5], Vertex[4][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, {PropagatorEndpoints -> Vertex}}\
    , {Vertex[1][3] -> {20, 15}, Vertex[1][4] -> {20, 10}, 
    Vertex[1][5] -> {20, 5}, Vertex[1][1] -> {0, 15}, 
    Vertex[1][2] -> {0, 5}, Vertex[4][4] -> {7, 12}, Vertex[3][5] -> {13, 8}}\
    , {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][5]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][5], Vertex[4][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{10, 9}}]}}, 
   {Vertex[4][4] -> {7, 10}, Vertex[3][5] -> {13, 10}, 
    Vertex[1][3] -> {20, 15}, Vertex[1][4] -> {20, 10}, 
    Vertex[1][5] -> {20, 5}, Vertex[1][1] -> {0, 15}, Vertex[1][2] -> {0, 5}}\
    , {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][5]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][5]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[4][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[4][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, {PropagatorEndpoints -> Vertex}}\
    , {Vertex[1][3] -> {20, 15}, Vertex[1][4] -> {20, 10}, 
    Vertex[1][5] -> {20, 5}, Vertex[1][1] -> {0, 15}, 
    Vertex[1][2] -> {0, 5}, Vertex[4][5] -> {10, 13}, 
    Vertex[3][1] -> {10, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][5]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][5]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[4][5]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, {PropagatorEndpoints -> Vertex}}\
    , {Vertex[1][3] -> {20, 15}, Vertex[1][4] -> {20, 10}, 
    Vertex[1][5] -> {20, 5}, Vertex[1][1] -> {0, 15}, 
    Vertex[1][2] -> {0, 5}, Vertex[4][5] -> {10, 13}, 
    Vertex[3][4] -> {10, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][5]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][5]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[4][5]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, {PropagatorEndpoints -> Vertex}}\
    , {Vertex[4][5] -> {7, 10}, Vertex[3][4] -> {13, 10}, 
    Vertex[1][3] -> {20, 15}, Vertex[1][4] -> {20, 10}, 
    Vertex[1][5] -> {20, 5}, Vertex[1][1] -> {0, 15}, Vertex[1][2] -> {0, 5}}\
    , {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][4], Vertex[3][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[3][1] -> {5, 10}, Vertex[3][5] -> {10, 10}, 
    Vertex[3][4] -> {15, 10}, Vertex[1][3] -> {20, 15}, 
    Vertex[1][4] -> {20, 10}, Vertex[1][5] -> {20, 5}, 
    Vertex[1][1] -> {0, 15}, Vertex[1][2] -> {0, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][5]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[3][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[3][1] -> {5, 10}, Vertex[3][4] -> {10, 10}, 
    Vertex[3][5] -> {15, 10}, Vertex[1][3] -> {20, 15}, 
    Vertex[1][4] -> {20, 10}, Vertex[1][5] -> {20, 5}, 
    Vertex[1][1] -> {0, 15}, Vertex[1][2] -> {0, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][5]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[3][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[3][1] -> {5, 10}, Vertex[1][3] -> {20, 15}, 
    Vertex[1][4] -> {20, 10}, Vertex[1][5] -> {20, 5}, 
    Vertex[1][1] -> {0, 15}, Vertex[1][2] -> {0, 5}, 
    Vertex[3][4] -> {10, 12}, Vertex[3][5] -> {15, 8}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][4], Vertex[3][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][3] -> {20, 15}, Vertex[1][4] -> {20, 10}, 
    Vertex[1][5] -> {20, 5}, Vertex[1][1] -> {0, 15}, 
    Vertex[1][2] -> {0, 5}, Vertex[3][1] -> {10, 15}, 
    Vertex[3][4] -> {10, 5}, Vertex[3][5] -> {10, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][5]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[3][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[3][4] -> {7, 7}, Vertex[1][3] -> {20, 15}, 
    Vertex[1][4] -> {20, 10}, Vertex[1][5] -> {20, 5}, 
    Vertex[1][1] -> {0, 15}, Vertex[1][2] -> {0, 5}, 
    Vertex[3][1] -> {10, 15}, Vertex[3][5] -> {13, 6}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][5]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[3][1] -> {7, 13}, Vertex[1][3] -> {20, 15}, 
    Vertex[1][4] -> {20, 10}, Vertex[1][5] -> {20, 5}, 
    Vertex[1][1] -> {0, 15}, Vertex[1][2] -> {0, 5}, 
    Vertex[3][4] -> {10, 5}, Vertex[3][5] -> {13, 14}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][5]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[3][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][3] -> {20, 15}, Vertex[1][4] -> {20, 10}, 
    Vertex[1][5] -> {20, 5}, Vertex[1][1] -> {0, 15}, 
    Vertex[1][2] -> {0, 5}, Vertex[3][1] -> {10, 15}, 
    Vertex[3][5] -> {10, 5}, Vertex[3][4] -> {10, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][5]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][3] -> {20, 15}, Vertex[1][4] -> {20, 10}, 
    Vertex[1][5] -> {20, 5}, Vertex[1][1] -> {0, 15}, 
    Vertex[1][2] -> {0, 5}, Vertex[3][1] -> {7, 15}, Vertex[3][5] -> {7, 5}, 
    Vertex[3][4] -> {13, 12}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][4], Vertex[3][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{5, 6.}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{17., 14.}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{18., 9.7}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{17., 7.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{8.8, 7.5}}]}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][3] -> {20, 15}, Vertex[1][4] -> {20, 10}, 
    Vertex[1][5] -> {20, 5}, Vertex[3][5] -> {10, 10}, 
    Vertex[3][4] -> {10, 15}, Vertex[3][1] -> {10, 5}, 
    Vertex[1][1] -> {0, 15}, Vertex[1][2] -> {0, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][5]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[3][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{17., 14.3}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{18., 10.8}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{18., 6.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{7.6, 10.}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{10., 12.3}}]}}, 
   {Vertex[1][3] -> {20, 15}, Vertex[1][4] -> {20, 10}, 
    Vertex[1][5] -> {20, 5}, Vertex[1][1] -> {0, 15}, 
    Vertex[1][2] -> {0, 5}, Vertex[3][4] -> {7, 15}, Vertex[3][1] -> {7, 5}, 
    Vertex[3][5] -> {13, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][5]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[3][5] -> {13, 10}, Vertex[1][3] -> {20, 15}, 
    Vertex[1][4] -> {20, 10}, Vertex[1][5] -> {20, 5}, 
    Vertex[1][1] -> {0, 15}, Vertex[1][2] -> {0, 5}, 
    Vertex[3][4] -> {7, 15}, Vertex[3][1] -> {7, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][5]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][3] -> {20, 15}, Vertex[1][4] -> {20, 10}, 
    Vertex[1][5] -> {20, 5}, Vertex[3][4] -> {10, 15}, 
    Vertex[3][5] -> {10, 5}, Vertex[3][1] -> {10, 10}, 
    Vertex[1][1] -> {0, 15}, Vertex[1][2] -> {0, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][5]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[3][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{5, 14.2}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{5, 6.}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{17., 14.}}], 
     PropagatorHeight -> 0.3}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{18., 11.2}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{17., 6.}}], 
     PropagatorHeight -> -0.3}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{10.7, 8.}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{10.7, 12.}}]}}, 
   {Vertex[1][4] -> {20, 10}, Vertex[1][1] -> {0, 15}, 
    Vertex[1][2] -> {0, 5}, Vertex[3][4] -> {10, 10}, 
    Vertex[3][1] -> {10, 5}, Vertex[3][5] -> {10, 15}, 
    Vertex[1][5] -> {20, 5}, Vertex[1][3] -> {20, 15}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][5]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{3.5, 8.8}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{3.5, 6.}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{17., 14.}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{18., 10.8}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{17., 5.5}}]}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{7.5, 10.}}]}}, 
   {Vertex[1][3] -> {20, 15}, Vertex[1][4] -> {20, 10}, 
    Vertex[1][5] -> {20, 5}, Vertex[1][1] -> {0, 15}, 
    Vertex[1][2] -> {0, 5}, Vertex[3][5] -> {7, 15}, Vertex[3][1] -> {7, 5}, 
    Vertex[3][4] -> {12, 8}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][5]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{5, 6.}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{16., 14.3}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{18., 10.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{17.5, 5.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{8.7, 7.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{8.7, 12.5}}]}}, 
   {Vertex[1][3] -> {20, 15}, Vertex[1][4] -> {20, 10}, 
    Vertex[1][5] -> {20, 5}, Vertex[1][1] -> {0, 15}, 
    Vertex[1][2] -> {0, 5}, Vertex[3][5] -> {10, 15}, 
    Vertex[3][1] -> {10, 10}, Vertex[3][4] -> {10, 5}}, {}}
 
GraphPoints[_Topology] := $Undefined
 
 
