GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[6][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[6][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[6][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[6][4]], 
    Propagator[Loop[1]][Vertex[6][4], Vertex[6][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}, PropagatorHeight -> -1}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, PropagatorHeight -> 1}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 4}}, 
   {Vertex[1][1] -> {0, 15}, Vertex[1][3] -> {20, 15}, 
    Vertex[1][4] -> {20, 5}, Vertex[1][2] -> {0, 5}, 
    Vertex[6][4] -> {10, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[4][4]]]] = 
  {{Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[4][2] -> {6, 10.}, Vertex[4][4] -> {14, 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[4][2], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[4][2] -> {7, 12.}, Vertex[4][4] -> {13, 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[4][3], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][4], Vertex[4][4]]]] = 
  {{Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[4][3] -> {7, 10.}, Vertex[4][4] -> {13, 8.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][3], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][3], Vertex[4][4]]]] = 
  {{Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[4][3] -> {10, 13.}, Vertex[4][4] -> {10, 7.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[4][2], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[4][2] -> {7, 8.}, Vertex[4][4] -> {13, 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][3], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][3], Vertex[4][4]]]] = 
  {{Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[4][3] -> {10., 7.}, Vertex[4][4] -> {10., 13.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[4][3], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][3], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[4][3] -> {14., 13.}, Vertex[4][4] -> {7., 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][4]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {7., 15.}, Vertex[3][2] -> {7., 5.}, 
    Vertex[4][4] -> {13., 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][4]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {5., 14.}, Vertex[3][3] -> {10., 7.}, 
    Vertex[4][4] -> {10., 13.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {7, 14.}, Vertex[3][4] -> {10., 6.}, 
    Vertex[4][3] -> {13, 13.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {6., 13.}, Vertex[3][4] -> {15, 10.}, 
    Vertex[4][3] -> {9., 8.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][4], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {7., 13.}, Vertex[3][4] -> {13., 13.}, 
    Vertex[4][3] -> {10., 7.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[4][4]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {7, 12.}, Vertex[3][3] -> {13, 12.}, 
    Vertex[4][4] -> {10, 7.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {5., 13.}, Vertex[3][2] -> {10., 12.}, 
    Vertex[4][4] -> {15., 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][4], Vertex[4][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {Propagator3rdPoint -> {17, 12}, PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][2] -> {5, 10.}, Vertex[3][3] -> {10., 13.}, 
    Vertex[4][4] -> {15., 9.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[4][4]]]] = 
  {{{PropagatorLabelPosition -> ComposedChar[{{3., 13.}}], 
     PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorLabelPosition -> ComposedChar[{{3., 6.8}}], 
     PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorLabelPosition -> ComposedChar[{{17., 5.8}}], 
     PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorLabelPosition -> ComposedChar[{{17., 9.5}}], 
     PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 14.}, Vertex[1][2] -> {0, 6.}, 
    Vertex[1][3] -> {20., 14.}, Vertex[1][4] -> {20., 6.}, 
    Vertex[3][2] -> {6., 10.}, Vertex[3][3] -> {15., 12.}, 
    Vertex[4][4] -> {13, 8.}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[4][3]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[4][3], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][2] -> {4, 10.}, Vertex[3][4] -> {17, 10.}, 
    Vertex[4][3] -> {10, 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[4][3], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][2] -> {5, 10.}, Vertex[3][4] -> {11., 8.}, 
    Vertex[4][3] -> {15., 12.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][4], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][4], Vertex[4][3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][2] -> {5., 10.}, Vertex[3][4] -> {15., 8.}, 
    Vertex[4][3] -> {12., 13.}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {10, 10.}, Vertex[3][2] -> {4, 10.}, 
    Vertex[4][4] -> {16, 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, {Propagator3rdPoint -> {8, 17}}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {11., 14.}, Vertex[3][2] -> {6, 10.}, 
    Vertex[4][4] -> {15, 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][4], Vertex[4][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {Propagator3rdPoint -> {12, 5}, PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][2] -> {7, 12.}, Vertex[3][3] -> {7, 7.}, 
    Vertex[4][4] -> {14, 9.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[4][3], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][2] -> {7, 12.}, Vertex[3][4] -> {7, 6.}, 
    Vertex[4][3] -> {13, 14.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, Propagator3rdPoint -> {11, 18}}}, 
   {Vertex[1][1] -> {0, 13.}, Vertex[1][2] -> {0, 3.}, 
    Vertex[1][3] -> {20, 13.}, Vertex[1][4] -> {20, 3.}, 
    Vertex[3][1] -> {9., 14.}, Vertex[3][2] -> {7, 10.}, 
    Vertex[4][4] -> {14., 7.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][4], Vertex[4][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {Propagator3rdPoint -> {15, 11}, PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][2] -> {7, 9.}, Vertex[3][3] -> {10., 13.}, 
    Vertex[4][4] -> {14., 7.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][4]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][2] -> {7, 6.}, Vertex[3][3] -> {10., 14.}, 
    Vertex[4][4] -> {13, 8.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][2]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[4][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {Propagator3rdPoint -> {7, 10}, PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][3] -> {10, 14.}, Vertex[3][4] -> {10., 6.}, 
    Vertex[4][2] -> {10, 10.}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][3] -> {12., 13.}, Vertex[3][4] -> {12., 7.}, 
    Vertex[4][2] -> {6., 6.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][4], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][4], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][3] -> {9, 13.}, Vertex[3][4] -> {13, 6.}, 
    Vertex[4][2] -> {7, 7.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][3] -> {10., 11.}, Vertex[3][4] -> {15, 11.}, 
    Vertex[4][2] -> {5., 8.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][4]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 16.}, Vertex[1][2] -> {0, 4.}, 
    Vertex[1][3] -> {20., 16.}, Vertex[1][4] -> {20., 4.}, 
    Vertex[3][1] -> {10, 10.}, Vertex[3][3] -> {10., 15.}, 
    Vertex[4][4] -> {10., 5.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {Propagator3rdPoint -> {10, 2}, PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 17.}, Vertex[1][2] -> {0, 7.}, 
    Vertex[1][3] -> {20, 17.}, Vertex[1][4] -> {20, 7.}, 
    Vertex[3][1] -> {10, 6.}, Vertex[3][3] -> {10., 15.}, 
    Vertex[4][4] -> {10, 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[4][3], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][2] -> {7, 8.}, Vertex[3][4] -> {7, 12.}, 
    Vertex[4][3] -> {13, 12.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][2] -> {5., 7.}, Vertex[3][4] -> {10., 13.}, 
    Vertex[4][3] -> {10., 9.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][2]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][3] -> {10., 6.}, Vertex[3][4] -> {10., 14.}, 
    Vertex[4][2] -> {10, 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][3] -> {14., 13.}, Vertex[3][4] -> {6., 13.}, 
    Vertex[4][2] -> {7., 9.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][3] -> {14., 13.}, Vertex[3][4] -> {8., 6.}, 
    Vertex[4][2] -> {8., 11.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 16.}, Vertex[1][2] -> {0, 4.}, 
    Vertex[1][3] -> {20., 16.}, Vertex[1][4] -> {20., 4.}, 
    Vertex[3][1] -> {8., 10.}, Vertex[3][4] -> {10., 15.}, 
    Vertex[4][3] -> {10., 5.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[4][3]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {10., 5.}, Vertex[3][4] -> {10., 14.}, 
    Vertex[4][3] -> {10., 9.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][3] -> {12., 6.}, Vertex[3][4] -> {12., 13.}, 
    Vertex[4][2] -> {6., 14.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][4], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][4], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][3] -> {8., 14.}, Vertex[3][4] -> {14., 7.}, 
    Vertex[4][2] -> {8., 9.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][3] -> {10., 9.}, Vertex[3][4] -> {15., 9.}, 
    Vertex[4][2] -> {5., 12.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][3] -> {12., 13.}, Vertex[3][4] -> {12., 6.}, 
    Vertex[4][2] -> {6., 14.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][3] -> {14., 14.}, Vertex[3][4] -> {8., 7.}, 
    Vertex[4][2] -> {8., 13.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][4], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][3] -> {13., 13.}, Vertex[3][4] -> {13., 7.}, 
    Vertex[4][2] -> {6., 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][3] -> {10, 10.}, Vertex[3][4] -> {16, 10.}, 
    Vertex[4][2] -> {4, 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][2] -> {5., 9.}, Vertex[3][4] -> {15., 10.}, 
    Vertex[4][3] -> {9., 13.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][4], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][2] -> {7, 8.}, Vertex[3][4] -> {13, 8.}, 
    Vertex[4][3] -> {10, 13.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[4][3]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 13.}, Vertex[1][2] -> {0, 3.}, 
    Vertex[1][3] -> {20, 13.}, Vertex[1][4] -> {20, 3.}, 
    Vertex[3][1] -> {10, 14.}, Vertex[3][4] -> {10., 4.}, 
    Vertex[4][3] -> {10., 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 16.}, Vertex[1][2] -> {0, 4.}, 
    Vertex[1][3] -> {20., 16.}, Vertex[1][4] -> {20., 4.}, 
    Vertex[3][2] -> {10., 10.}, Vertex[3][4] -> {10., 5.}, 
    Vertex[4][3] -> {10., 15.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[4][3]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {9., 14.}, Vertex[3][4] -> {15, 10.}, 
    Vertex[4][3] -> {5., 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {11., 4.}, Vertex[3][4] -> {13, 8.}, 
    Vertex[4][3] -> {6., 11.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {10., 8.}, Vertex[3][4] -> {15, 7.}, 
    Vertex[4][3] -> {5., 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[4][4]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][2] -> {7, 6.}, Vertex[3][3] -> {13, 6.}, 
    Vertex[4][4] -> {10, 12.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {Propagator3rdPoint -> {11, 3}, PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 17.}, Vertex[1][2] -> {0, 7.}, 
    Vertex[1][3] -> {20, 17.}, Vertex[1][4] -> {20, 7.}, 
    Vertex[3][1] -> {9., 7.}, Vertex[3][2] -> {7, 10.}, 
    Vertex[4][4] -> {14., 13.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {10, 9.}, Vertex[3][2] -> {5, 7.}, 
    Vertex[4][4] -> {15, 11.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, Propagator3rdPoint -> {10, 18}}}, 
   {Vertex[1][1] -> {0, 13.}, Vertex[1][2] -> {0, 3.}, 
    Vertex[1][3] -> {20, 13.}, Vertex[1][4] -> {20, 3.}, 
    Vertex[3][1] -> {10., 14.}, Vertex[3][3] -> {10., 4.}, 
    Vertex[4][4] -> {10., 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][4]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 18.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 18.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][2] -> {9., 16.}, Vertex[3][3] -> {14, 16.}, 
    Vertex[4][4] -> {5, 12.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, {Propagator3rdPoint -> {9, 18}}}, 
   {Vertex[1][1] -> {0, 13.}, Vertex[1][2] -> {0, 3.}, 
    Vertex[1][3] -> {20, 13.}, Vertex[1][4] -> {20, 3.}, 
    Vertex[3][1] -> {11., 14.}, Vertex[3][3] -> {13, 10.}, 
    Vertex[4][4] -> {6., 7.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]]]] = 
  {{{PropagatorLabelPosition -> ComposedChar[{{3., 13.}}], 
     PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorLabelPosition -> ComposedChar[{{3., 6.200000000000001}}], 
     PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorLabelPosition -> ComposedChar[{{13., 6.200000000000001}}], 
     PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorLabelPosition -> ComposedChar[{{10.5, 14.8}}], 
     PropagatorEndpoints -> Vertex}, 
    {PropagatorLabelPosition -> ComposedChar[{{14.5, 10.3}}], 
     PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {10., 12.}, Vertex[3][3] -> {15, 13.}, 
    Vertex[4][4] -> {5., 10.}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[3][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {6., 14.}, Vertex[3][2] -> {6., 6.}, 
    Vertex[3][3] -> {14., 14.}, Vertex[3][4] -> {14., 6.}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[3][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorLabelPosition -> ComposedChar[{{2.8, 6.8}}], 
     PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorLabelPosition -> ComposedChar[{{17., 13.3}}], 
     PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorLabelPosition -> ComposedChar[{{17., 6.5}}], 
     PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorLabelPosition -> ComposedChar[{{9.5, 7.}}], 
     PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12, 10}}]}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {6., 14.}, Vertex[3][2] -> {6., 6.}, 
    Vertex[3][3] -> {13., 6.}, Vertex[3][4] -> {13., 14.}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{3.5, 14.2}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{3.5, 5.6}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{17., 14.2}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{17., 5.8}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{10.5, 12.}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12.5, 9.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{7.5, 9.5}}]}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 16.}, Vertex[1][2] -> {0, 4.}, 
    Vertex[1][3] -> {20., 16.}, Vertex[1][4] -> {20., 4.}, 
    Vertex[3][1] -> {14., 13.}, Vertex[3][2] -> {7., 5.}, 
    Vertex[3][3] -> {7., 13.}, Vertex[3][4] -> {14., 5.}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][2] -> {4, 7.}, Vertex[3][1] -> {4, 13.}, 
    Vertex[3][3] -> {10, 10.}, Vertex[3][4] -> {16, 10.}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorLabelPosition -> ComposedChar[{{2.5, 7.5}}], 
     PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorLabelPosition -> ComposedChar[{{17., 6.8}}], 
     PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12.5, 13.}}]}, 
    {PropagatorLabelPosition -> ComposedChar[{{6.5, 13.}}], 
     PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorLabelPosition -> ComposedChar[{{6.5, 11.3}}], 
     PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {5., 15.}, Vertex[3][2] -> {10., 12.}, 
    Vertex[3][3] -> {15., 12.}, Vertex[3][4] -> {5., 9.}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {5., 14.}, Vertex[3][2] -> {9., 13.}, 
    Vertex[3][3] -> {14., 7.}, Vertex[3][4] -> {14, 12.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {4, 14.}, Vertex[3][2] -> {7, 11.}, 
    Vertex[3][3] -> {10., 8.}, Vertex[3][4] -> {16., 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {5., 13.}, Vertex[3][2] -> {10., 12.}, 
    Vertex[3][3] -> {15., 10.}, Vertex[3][4] -> {10., 7.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{3.5, 13.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{3.5, 6.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{17., 13.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{17., 6.5}}]}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {7, 14.}, Vertex[3][2] -> {10, 10.}, 
    Vertex[3][3] -> {13, 14.}, Vertex[3][4] -> {10, 6.}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[3][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{2., 13.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{2., 6.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{17., 15.}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{17., 5.}}]}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12., 12.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12., 7.5}}]}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {10, 10.}, Vertex[3][2] -> {4, 10.}, 
    Vertex[3][3] -> {15., 13.}, Vertex[3][4] -> {15, 7.}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]]]] = 
  {{Null, Null, Null, Null, Null, Null, {PropagatorHeight -> 2}, 
    {PropagatorHeight -> -2}}, {Vertex[1][1] -> {0, 15.}, 
    Vertex[1][2] -> {0, 5.}, Vertex[1][3] -> {20, 15.}, 
    Vertex[1][4] -> {20, 5.}, Vertex[3][1] -> {12., 9.}, 
    Vertex[3][2] -> {4., 10.}, Vertex[3][3] -> {10., 13.}, 
    Vertex[3][4] -> {16., 7.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, 
    {Propagator3rdPoint -> {11, 18}}}, 
   {Vertex[1][1] -> {0, 13.}, Vertex[1][2] -> {0, 3.}, 
    Vertex[1][3] -> {20., 14.}, Vertex[1][4] -> {20., 3.}, 
    Vertex[3][1] -> {13., 14.}, Vertex[3][2] -> {5., 8.}, 
    Vertex[3][3] -> {15., 11.}, Vertex[3][4] -> {10., 8.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, 
    {Propagator3rdPoint -> {11, 3}}}, 
   {Vertex[1][1] -> {0, 17.}, Vertex[1][2] -> {0, 7.}, 
    Vertex[1][3] -> {20, 17.}, Vertex[1][4] -> {20, 7.}, 
    Vertex[3][1] -> {13., 6.}, Vertex[3][2] -> {5., 13.}, 
    Vertex[3][3] -> {10., 13.}, Vertex[3][4] -> {15., 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {12, 12.}, Vertex[3][2] -> {4., 10.}, 
    Vertex[3][3] -> {16, 14.}, Vertex[3][4] -> {10., 8.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {7, 10.}, Vertex[3][2] -> {2, 10.}, 
    Vertex[3][3] -> {12, 10.}, Vertex[3][4] -> {18, 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, 
    {Propagator3rdPoint -> {10, 2}}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {10., 6.}, Vertex[3][2] -> {4, 10.}, 
    Vertex[3][3] -> {10, 10.}, Vertex[3][4] -> {16, 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]]]] = 
  {{Null, Null, Null, Null, Null, Null, {PropagatorHeight -> 2}, 
    {PropagatorHeight -> -2}}, {Vertex[1][1] -> {0, 17.}, 
    Vertex[1][2] -> {0, 5.}, Vertex[1][3] -> {20, 17.}, 
    Vertex[1][4] -> {20, 5.}, Vertex[3][1] -> {10., 9.}, 
    Vertex[3][2] -> {6, 12.}, Vertex[3][3] -> {6, 8.}, 
    Vertex[3][4] -> {15, 7.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, 
    {Propagator3rdPoint -> {5, 7}}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {6., 10.}, Vertex[3][2] -> {7., 14.}, 
    Vertex[3][3] -> {14., 6.}, Vertex[3][4] -> {14., 13.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, 
    {Propagator3rdPoint -> {9, 3}}}, 
   {Vertex[1][1] -> {0, 17.}, Vertex[1][2] -> {0, 7.}, 
    Vertex[1][3] -> {20, 17.}, Vertex[1][4] -> {20, 7.}, 
    Vertex[3][1] -> {11., 7.}, Vertex[3][2] -> {6., 15.}, 
    Vertex[3][3] -> {6, 10.}, Vertex[3][4] -> {13., 11.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, 
    {Propagator3rdPoint -> {9, 16}}}, 
   {Vertex[1][1] -> {0, 13.}, Vertex[1][2] -> {0, 3.}, 
    Vertex[1][3] -> {20, 13.}, Vertex[1][4] -> {20, 3.}, 
    Vertex[3][1] -> {7., 13.}, Vertex[3][2] -> {4., 10.}, 
    Vertex[3][3] -> {8., 7.}, Vertex[3][4] -> {15, 7.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, 
    {Propagator3rdPoint -> {5, 7}}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {6, 10.}, Vertex[3][2] -> {7, 14.}, 
    Vertex[3][3] -> {14., 13.}, Vertex[3][4] -> {14., 6.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {10., 13.}, Vertex[3][2] -> {5., 12.}, 
    Vertex[3][3] -> {15., 14.}, Vertex[3][4] -> {10., 7.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, 
    {Propagator3rdPoint -> {15, 7}}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {14, 10.}, Vertex[3][2] -> {6., 13.}, 
    Vertex[3][3] -> {13, 14.}, Vertex[3][4] -> {6., 6.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorHeight -> 2, PropagatorEndpoints -> Vertex}, 
    {PropagatorHeight -> -2, PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 6.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20., 6.}, 
    Vertex[3][1] -> {10, 8.}, Vertex[3][2] -> {5., 9.}, 
    Vertex[3][3] -> {10., 13.}, Vertex[3][4] -> {15., 7.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, 
    {Propagator3rdPoint -> {7, 1}, PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 18.}, Vertex[1][2] -> {0, 8.}, 
    Vertex[1][3] -> {20., 18.}, Vertex[1][4] -> {20., 8.}, 
    Vertex[3][1] -> {6., 5.}, Vertex[3][2] -> {5., 9.}, 
    Vertex[3][3] -> {10, 16.}, Vertex[3][4] -> {10, 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {10, 10.}, Vertex[3][2] -> {7, 6.}, 
    Vertex[3][3] -> {10, 15.}, Vertex[3][4] -> {13, 6.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, 
    {Propagator3rdPoint -> {11, 2}, PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 18.}, Vertex[1][2] -> {0, 8.}, 
    Vertex[1][3] -> {20, 18.}, Vertex[1][4] -> {20, 8.}, 
    Vertex[3][1] -> {12., 6.}, Vertex[3][2] -> {8., 12.}, 
    Vertex[3][3] -> {8., 17.}, Vertex[3][4] -> {14, 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {9., 8.}, Vertex[3][2] -> {5., 6.}, 
    Vertex[3][3] -> {13., 14.}, Vertex[3][4] -> {13., 9.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, 
    {Propagator3rdPoint -> {9, 3}, PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 16.}, Vertex[1][2] -> {0, 6.}, 
    Vertex[1][3] -> {20, 16.}, Vertex[1][4] -> {20, 6.}, 
    Vertex[3][1] -> {7., 6.}, Vertex[3][2] -> {4, 9.}, 
    Vertex[3][3] -> {8, 12.}, Vertex[3][4] -> {15, 12.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {8., 10.}, Vertex[3][2] -> {5., 7.}, 
    Vertex[3][3] -> {10., 14.}, Vertex[3][4] -> {15., 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, 
    {Propagator3rdPoint -> {2, 11}, PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 17.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 17.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {6., 11.}, Vertex[3][2] -> {10, 11.}, 
    Vertex[3][3] -> {10, 16.}, Vertex[3][4] -> {10, 6.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 16.}, Vertex[1][2] -> {0, 4.}, 
    Vertex[1][3] -> {20., 16.}, Vertex[1][4] -> {20., 4.}, 
    Vertex[3][1] -> {10, 12.}, Vertex[3][2] -> {10, 8.}, 
    Vertex[3][3] -> {10., 15.}, Vertex[3][4] -> {10., 5.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, 
    {Propagator3rdPoint -> {7, 1}, PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 18.}, Vertex[1][2] -> {0, 8.}, 
    Vertex[1][3] -> {20., 18.}, Vertex[1][4] -> {20., 8.}, 
    Vertex[3][1] -> {6., 5.}, Vertex[3][2] -> {5., 9.}, 
    Vertex[3][3] -> {10., 10.}, Vertex[3][4] -> {10., 16.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorHeight -> 2, PropagatorEndpoints -> Vertex}, 
    {PropagatorHeight -> -2, PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 17.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 17.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {10, 11.}, Vertex[3][2] -> {5, 8.}, 
    Vertex[3][3] -> {15, 14.}, Vertex[3][4] -> {5, 12.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, 
    {Propagator3rdPoint -> {10, 18}}}, 
   {Vertex[1][1] -> {0, 13.}, Vertex[1][2] -> {0, 3.}, 
    Vertex[1][3] -> {20., 13.}, Vertex[1][4] -> {20., 3.}, 
    Vertex[3][1] -> {12., 14.}, Vertex[3][2] -> {8., 7.}, 
    Vertex[3][3] -> {14., 10.}, Vertex[3][4] -> {8., 12.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorLabelPosition -> ComposedChar[{{17.2, 14.3}}], 
     PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorLabelPosition -> ComposedChar[{{17.2, 7.3}}], 
     PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorLabelPosition -> ComposedChar[{{13.2, 12.}}], 
     PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {10., 8.}, Vertex[3][2] -> {5., 7.}, 
    Vertex[3][3] -> {14., 10.}, Vertex[3][4] -> {14., 14.}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{3.5, 13.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{3.5, 6.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{18.5, 11.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{18.5, 7.}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{8.8, 11.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{7., 8.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12., 8.5}}]}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {10, 10.}, Vertex[3][2] -> {7, 6.}, 
    Vertex[3][3] -> {13, 6.}, Vertex[3][4] -> {10, 13.}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, 
    {Propagator3rdPoint -> {10, 18}}}, 
   {Vertex[1][1] -> {0, 13.}, Vertex[1][2] -> {0, 3.}, 
    Vertex[1][3] -> {20, 13.}, Vertex[1][4] -> {20, 3.}, 
    Vertex[3][1] -> {10., 14.}, Vertex[3][2] -> {10, 10.}, 
    Vertex[3][3] -> {14, 10.}, Vertex[3][4] -> {6, 10.}}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 15.}, Vertex[1][2] -> {0, 5.}, 
    Vertex[1][3] -> {20, 15.}, Vertex[1][4] -> {20, 5.}, 
    Vertex[3][1] -> {8, 14.}, Vertex[3][2] -> {12, 14.}, 
    Vertex[3][3] -> {16., 14.}, Vertex[3][4] -> {4., 14.}}}
 
GraphPoints[_Topology] := $Undefined
 
