GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][5], Vertex[3][5]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][5]], 
    Propagator[Loop[1]][Vertex[3][4], Vertex[3][5]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 15}, Vertex[1][4] -> {20, 10}, 
    Vertex[1][5] -> {20, 5}, Vertex[3][2] -> {5, 7}, 
    Vertex[3][3] -> {5, 13}, Vertex[3][4] -> {15, 10}, 
    Vertex[3][1] -> {10, 7}, Vertex[3][5] -> {15, 5}}, {}}
 
GraphPoints[_Topology] := $Undefined
