GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[6][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[6][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[6][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[6][4]], 
    Propagator[Loop[2]][Vertex[6][4], Vertex[6][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[3][1] -> {6, 13}, Vertex[3][2] -> {6, 7}, 
    Vertex[6][4] -> {13, 12}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[4][-1], Vertex[4][4]], 
    Propagator[Loop[2]][Vertex[4][-1], Vertex[4][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[3][1] -> {5, 13}, Vertex[3][2] -> {5, 7}, 
    Vertex[4][-1] -> {10, 10}, Vertex[4][4] -> {15, 10}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][-1], Vertex[4][4]], 
    Propagator[Loop[2]][Vertex[4][-1], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[4][4] -> {13, 10}, Vertex[1][3] -> {20, 13}, 
    Vertex[1][4] -> {20, 7}, Vertex[3][1] -> {7, 13}, 
    Vertex[3][2] -> {7, 7}, Vertex[4][-1] -> {11, 14}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[4][-1], Vertex[4][4]], 
    Propagator[Loop[2]][Vertex[4][-1], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, Propagator3rdPoint -> {11, 3}}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[4][4] -> {13, 10}, Vertex[1][3] -> {20, 13}, 
    Vertex[1][4] -> {20, 7}, Vertex[3][1] -> {6, 13}, 
    Vertex[3][2] -> {6, 7}, Vertex[4][-1] -> {10.5, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[2]][Vertex[4][-1], Vertex[4][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 2}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, Vertex[3][2] -> {7, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[3][1] -> {5, 13}, Vertex[4][-1] -> {10, 13}, 
    Vertex[4][4] -> {14, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[2]][Vertex[4][-1], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -3}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[4][4] -> {13, 10}, Vertex[1][3] -> {20, 13}, 
    Vertex[1][4] -> {20, 7}, Vertex[3][1] -> {7, 13}, 
    Vertex[3][2] -> {7, 8}, Vertex[4][-1] -> {7, 4}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][4]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][-1], Vertex[4][4]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -2}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[4][4] -> {14, 10}, Vertex[3][2] -> {4, 7}, 
    Vertex[3][1] -> {8, 13}, Vertex[4][-1] -> {9, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][-1], Vertex[4][4]], 
    Propagator[Loop[2]][Vertex[4][-1], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 3}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[3][3] -> {12, 7}, Vertex[4][4] -> {12, 11}, 
    Vertex[4][-1] -> {11, 14}, Vertex[3][1] -> {6, 13}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[4][-1], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[4][-1], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 3}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[4][-1] -> {8, 16}, Vertex[3][1] -> {4, 13}, 
    Vertex[4][3] -> {12, 13}, Vertex[3][4] -> {12, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][-1], Vertex[4][4]], 
    Propagator[Loop[2]][Vertex[4][-1], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -3}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[3][3] -> {13, 13}, Vertex[3][2] -> {5, 7}, 
    Vertex[4][4] -> {13, 8}, Vertex[4][-1] -> {9, 4}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[4][-1], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[4][-1], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -3}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[3][2] -> {5, 7}, Vertex[4][3] -> {11, 8}, 
    Vertex[4][-1] -> {9, 4}, Vertex[3][4] -> {11, 13}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][4], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[4][-1], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -3}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[3][1] -> {6, 13}, Vertex[3][2] -> {6, 7}, 
    Vertex[3][3] -> {14, 13}, Vertex[3][4] -> {14, 7}, 
    Vertex[4][-1] -> {10, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[4][-1], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -3}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[3][1] -> {5, 13}, Vertex[3][2] -> {5, 7}, 
    Vertex[3][4] -> {12, 13}, Vertex[3][3] -> {12, 7}, 
    Vertex[4][-1] -> {8.5, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[2]][Vertex[3][3], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[3][4], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[3][1] -> {5, 13}, Vertex[3][2] -> {5, 7}, 
    Vertex[4][-1] -> {10, 10}, Vertex[3][3] -> {15, 13}, 
    Vertex[3][4] -> {15, 7}, Vertex[1][3] -> {20, 13}, 
    Vertex[1][4] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[2]][Vertex[3][4], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[3][1] -> {4, 13}, Vertex[4][-1] -> {8, 13}, 
    Vertex[3][2] -> {7, 7}, Vertex[3][3] -> {13, 7}, 
    Vertex[3][4] -> {13, 13}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[3][4], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1.5}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1.5}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[3][1] -> {4, 13}, Vertex[4][-1] -> {8, 13}, 
    Vertex[3][3] -> {10, 7}, Vertex[3][2] -> {10, 10}, 
    Vertex[3][4] -> {13, 13}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[3][3], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[3][1] -> {4, 13}, Vertex[3][3] -> {15, 13}, 
    Vertex[3][4] -> {11, 7}, Vertex[3][2] -> {11, 10}, 
    Vertex[4][-1] -> {8, 13}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[4][-1], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -3}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[3][2] -> {5, 7}, Vertex[4][-1] -> {9, 5}, 
    Vertex[3][3] -> {13, 7}, Vertex[3][1] -> {9, 10}, 
    Vertex[3][4] -> {9, 13}}, {}}
 
GraphPoints[_Topology] := $Undefined
 
