GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[4][2], Vertex[4][3]], 
    Propagator[Loop[3]][Vertex[4][2], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {7, 10}, 
    Vertex[4][2] -> {13, 13}, Vertex[4][3] -> {13, 7}, 
    Vertex[1][2] -> {20, 13}, Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][1]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[4][1], Vertex[4][3]], 
    Propagator[Loop[3]][Vertex[4][1], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][1] -> {7, 10}, 
    Vertex[3][2] -> {13, 13}, Vertex[4][3] -> {13, 7}, 
    Vertex[1][2] -> {20, 13}, Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[4][1], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[4][1]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][1] -> {7, 10}, 
    Vertex[3][-1] -> {13, 13}, Vertex[4][3] -> {13, 7}, 
    Vertex[1][2] -> {20, 13}, Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[4][3]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][2] -> {7, 10}, 
    Vertex[3][-1] -> {13, 13}, Vertex[4][3] -> {13, 7}, 
    Vertex[1][2] -> {20, 13}, Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[4][2]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][3] -> {7, 10}, 
    Vertex[3][-1] -> {13, 13}, Vertex[4][2] -> {13, 7}, 
    Vertex[1][2] -> {20, 13}, Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[4][3]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][-1] -> {10, 13}, Vertex[3][2] -> {10, 7}, 
    Vertex[4][3] -> {15, 10}, Vertex[1][2] -> {20, 13}, 
    Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[4][3]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][3]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][-1] -> {10, 13}, Vertex[4][3] -> {10, 7}, 
    Vertex[3][2] -> {15, 10}, Vertex[1][2] -> {20, 13}, 
    Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[4][3]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][2] -> {10, 13}, Vertex[4][3] -> {10, 7}, 
    Vertex[3][-1] -> {15, 10}, Vertex[1][2] -> {20, 13}, 
    Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[4][2]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][-1] -> {10, 13}, Vertex[3][3] -> {10, 7}, 
    Vertex[4][2] -> {15, 10}, Vertex[1][2] -> {20, 13}, 
    Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][3], Vertex[4][2]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][-1] -> {10, 13}, Vertex[4][2] -> {10, 7}, 
    Vertex[3][3] -> {15, 10}, Vertex[1][2] -> {20, 13}, 
    Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[4][2]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][2]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][3] -> {10, 13}, Vertex[4][2] -> {10, 7}, 
    Vertex[3][-1] -> {15, 10}, Vertex[1][2] -> {20, 13}, 
    Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[4][3]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][-2] -> {10, 13}, Vertex[3][-1] -> {10, 7}, 
    Vertex[4][3] -> {15, 10}, Vertex[1][2] -> {20, 13}, 
    Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][-2] -> {10, 13}, Vertex[4][3] -> {10, 7}, 
    Vertex[3][-1] -> {15, 10}, Vertex[1][2] -> {20, 13}, 
    Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[4][1]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[4][1]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][1] -> {5, 10}, 
    Vertex[3][-1] -> {10, 13}, Vertex[3][3] -> {10, 7}, 
    Vertex[3][2] -> {15, 10}, Vertex[1][2] -> {20, 13}, 
    Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][1]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][3], Vertex[4][1]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][1] -> {7, 10}, 
    Vertex[3][-1] -> {13, 15}, Vertex[3][2] -> {13, 10}, 
    Vertex[3][3] -> {13, 5}, Vertex[1][2] -> {20, 13}, 
    Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][1]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[4][1]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][1] -> {5, 10}, 
    Vertex[3][-1] -> {10, 13}, Vertex[3][2] -> {10, 7}, 
    Vertex[3][3] -> {15, 10}, Vertex[1][2] -> {20, 13}, 
    Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][2] -> {5, 10}, 
    Vertex[3][-2] -> {10, 13}, Vertex[3][3] -> {10, 7}, 
    Vertex[3][-1] -> {15, 10}, Vertex[1][2] -> {20, 13}, 
    Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[3][3]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{Null, Null, Null, Null, Null, Null, Null, Null}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][2] -> {5, 10}, 
    Vertex[3][-2] -> {10, 13}, Vertex[3][-1] -> {10, 7}, 
    Vertex[3][3] -> {15, 10}, Vertex[1][2] -> {20, 13}, 
    Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][3] -> {5, 10}, 
    Vertex[3][-2] -> {10, 13}, Vertex[3][2] -> {10, 7}, 
    Vertex[3][-1] -> {15, 10}, Vertex[1][2] -> {20, 13}, 
    Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][3] -> {5, 10}, 
    Vertex[3][-2] -> {10, 13}, Vertex[3][-1] -> {10, 7}, 
    Vertex[3][2] -> {15, 10}, Vertex[1][2] -> {20, 13}, 
    Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][3]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[3][3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][-2] -> {10, 13}, Vertex[3][-1] -> {10, 7}, 
    Vertex[3][2] -> {15, 13}, Vertex[3][3] -> {15, 7}, 
    Vertex[1][2] -> {20, 13}, Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][-2] -> {10, 13}, Vertex[3][-1] -> {10, 7}, 
    Vertex[3][2] -> {15, 13}, Vertex[3][3] -> {15, 7}, 
    Vertex[1][2] -> {20, 13}, Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[3][3]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][-2] -> {15, 13}, 
    Vertex[3][3] -> {15, 7}, Vertex[3][1] -> {5, 10}, 
    Vertex[1][3] -> {20, 5}, Vertex[1][2] -> {20, 15}, 
    Vertex[3][2] -> {10, 13}, Vertex[3][-1] -> {10, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{2.5, 11.2}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{17.5, 13}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{17.5, 6.5}}]}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12.5, 12}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12.5, 16}}]}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][-1] -> {10, 13}, Vertex[3][3] -> {10, 7}, 
    Vertex[3][-2] -> {15, 13}, Vertex[1][3] -> {20, 5}, 
    Vertex[3][2] -> {15, 7}, Vertex[1][2] -> {20, 15}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{18, 13.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{18, 6.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12, 12}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12, 8}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{7, 12.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{7, 7.5}}]}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][3] -> {10, 7}, Vertex[3][-2] -> {15, 13}, 
    Vertex[3][-1] -> {15, 7}, Vertex[1][2] -> {20, 15}, 
    Vertex[1][3] -> {20, 5}, Vertex[3][2] -> {10, 13}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{2.5, 11.2}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{18, 13.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{18, 10.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{14.2, 10.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{6.5, 7.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{6.5, 12.5}}]}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12.5, 4}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12.5, 8}}]}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[1][2] -> {20, 15}, Vertex[1][3] -> {20, 5}, 
    Vertex[3][2] -> {10, 13}, Vertex[3][3] -> {15, 13}, 
    Vertex[3][-1] -> {10, 7}, Vertex[3][-2] -> {15, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][-1] -> {10, 13}, Vertex[3][3] -> {10, 7}, 
    Vertex[1][3] -> {20, 5}, Vertex[1][2] -> {20, 15}, 
    Vertex[3][2] -> {15, 13}, Vertex[3][-2] -> {15, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][2] -> {4, 10}, 
    Vertex[3][1] -> {8, 10}, Vertex[3][-1] -> {12, 13}, 
    Vertex[3][3] -> {12, 7}, Vertex[3][-2] -> {16, 10}, 
    Vertex[1][2] -> {20, 15}, Vertex[1][3] -> {20, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][2] -> {4, 10}, 
    Vertex[3][3] -> {8, 10}, Vertex[3][1] -> {12, 10}, 
    Vertex[3][-2] -> {16, 13}, Vertex[3][-1] -> {16, 7}, 
    Vertex[1][2] -> {20, 13}, Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][2] -> {5, 10}, 
    Vertex[3][1] -> {10, 13}, Vertex[3][3] -> {10, 7}, 
    Vertex[3][-2] -> {15, 13}, Vertex[3][-1] -> {15, 7}, 
    Vertex[1][2] -> {20, 13}, Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][3] -> {4, 10}, 
    Vertex[3][2] -> {8, 10}, Vertex[3][1] -> {12, 10}, 
    Vertex[3][-2] -> {16, 13}, Vertex[3][-1] -> {16, 7}, 
    Vertex[1][2] -> {20, 13}, Vertex[1][3] -> {20, 7}}, {}}
 
GraphPoints[_Topology] := $Undefined
 
 
