GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][3], Vertex[3][4]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 18.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 11}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 4.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12.5, 16}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{6, 7.5}}]}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][3] -> {20, 10}, 
    Vertex[3][1] -> {5, 5}, Vertex[3][-1] -> {5, 10}, 
    Vertex[3][-2] -> {10, 15}, Vertex[3][3] -> {15, 10}, 
    Vertex[3][4] -> {15, 5}, Vertex[1][4] -> {20, 3}, 
    Vertex[3][2] -> {15, 15}, Vertex[1][2] -> {20, 17}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{2, 14}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 17.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 11}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 4.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12, 11}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{6.5, 6}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{10, 16}}]}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{14, 12.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12.5, 6}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{8, 10}}]}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][3] -> {20, 8}, 
    Vertex[3][1] -> {5, 15}, Vertex[3][4] -> {5, 5}, 
    Vertex[3][3] -> {15, 15}, Vertex[3][2] -> {15, 10}, 
    Vertex[1][2] -> {20, 17}, Vertex[1][4] -> {20, 3}, 
    Vertex[3][-1] -> {10, 5}, Vertex[3][-2] -> {10, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 17.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 9.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 4.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12.5, 16}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{6, 7.5}}]}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{14, 12.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{14, 7.5}}]}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][3] -> {20, 10}, 
    Vertex[3][2] -> {15, 10}, Vertex[1][2] -> {20, 17}, 
    Vertex[1][4] -> {20, 3}, Vertex[3][3] -> {15, 15}, 
    Vertex[3][4] -> {15, 5}, Vertex[3][-1] -> {5, 10}, 
    Vertex[3][1] -> {5, 5}, Vertex[3][-2] -> {10, 15}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 18}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 9.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 4.5}}]}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1, 
     PropagatorLabelPosition -> ComposedChar[{{10, 12.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{16, 7.5}}]}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{9, 14}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{15, 12}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{10.5, 7.5}}]}}, 
   {Vertex[1][3] -> {20, 10}, Vertex[3][1] -> {5, 5}, 
    Vertex[3][4] -> {15, 5}, Vertex[3][2] -> {5, 15}, 
    Vertex[1][2] -> {20, 17}, Vertex[3][3] -> {15, 15}, 
    Vertex[3][-2] -> {10, 10}, Vertex[3][-1] -> {15, 10}, 
    Vertex[1][4] -> {20, 3}, Vertex[1][1] -> {0, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 17.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 11.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 4.5}}]}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -2}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -2}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][3] -> {16, 10}, 
    Vertex[1][3] -> {20, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][-1] -> {12, 17}, Vertex[3][-2] -> {12, 12}, 
    Vertex[3][2] -> {12, 7.5}, Vertex[3][4] -> {12., 3}, 
    Vertex[1][2] -> {20, 17}, Vertex[1][4] -> {20, 3}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 18.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 4.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{14, 18.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{11, 14.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{11, 5.5}}]}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 2}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -2}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][3] -> {20, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][2] -> {12, 17}, Vertex[3][4] -> {12, 3}, 
    Vertex[3][3] -> {16, 17}, Vertex[1][2] -> {20, 17}, 
    Vertex[1][4] -> {20, 3}, Vertex[3][-2] -> {12, 12.5}, 
    Vertex[3][-1] -> {12, 7.5}, Vertex[1][1] -> {0, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][4]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 18.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 6}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{14, 18.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{11, 10.5}}]}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 2}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 2}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{11, 14.5}}]}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][3] -> {20, 10}, 
    Vertex[3][1] -> {5, 10}, Vertex[3][-1] -> {12, 3}, 
    Vertex[3][2] -> {12., 17}, Vertex[3][3] -> {16, 17}, 
    Vertex[1][2] -> {20, 17}, Vertex[1][4] -> {20, 3}, 
    Vertex[3][-2] -> {12, 8}, Vertex[3][4] -> {12, 12.5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 18}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 9.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 4.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{14, 18}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{13, 5.5}}]}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -0.6}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -2}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 0.55}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{8.5, 10.5}}]}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][3] -> {20, 10}, 
    Vertex[3][1] -> {5, 10}, Vertex[3][4] -> {12, 3}, 
    Vertex[1][4] -> {20, 3}, Vertex[3][2] -> {12, 17}, 
    Vertex[3][3] -> {16, 17.}, Vertex[1][2] -> {20, 17}, 
    Vertex[3][-2] -> {12., 8}, Vertex[3][-1] -> {7., 15}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 17.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 9.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 4.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{6.5, 7}}]}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{7, 9}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12.5, 17}}]}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{14, 12}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{11, 12}}]}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][3] -> {20, 10}, 
    Vertex[3][-2] -> {10, 15}, Vertex[3][4] -> {7, 3}, 
    Vertex[1][4] -> {20, 3}, Vertex[3][1] -> {3., 12.}, 
    Vertex[3][3] -> {15, 17}, Vertex[3][2] -> {15, 7}, 
    Vertex[1][2] -> {20, 17}, Vertex[3][-1] -> {10, 9}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 18.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 11}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 4.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{6.5, 7}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{13, 16.5}}]}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{11, 11.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{8.5, 17}}]}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][3] -> {20, 10}, 
    Vertex[3][4] -> {7, 3}, Vertex[1][4] -> {20, 3}, 
    Vertex[3][1] -> {3, 12}, Vertex[3][2] -> {15, 17}, 
    Vertex[1][2] -> {20, 17}, Vertex[3][3] -> {15, 7}, 
    Vertex[3][-1] -> {7, 14}, Vertex[3][-2] -> {12, 14}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 18}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 8}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 4.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{6.5, 7}}]}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 0.5, 
     PropagatorLabelPosition -> ComposedChar[{{12, 14}}]}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 0.5, 
     PropagatorLabelPosition -> ComposedChar[{{18, 10.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{8.5, 15.5}}]}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{17, 14.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{12.5, 10}}]}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][3] -> {20, 10}, 
    Vertex[3][4] -> {7, 3}, Vertex[1][4] -> {20, 3}, 
    Vertex[3][1] -> {3, 12}, Vertex[3][2] -> {15, 17}, 
    Vertex[1][2] -> {20, 17}, Vertex[3][3] -> {15, 7}, 
    Vertex[3][-2] -> {12.5, 12}, Vertex[3][-1] -> {17.5, 12}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][4]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][3]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[3][3]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 18.5}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 11}}]}, 
    {PropagatorEndpoints -> {None, Vertex}, 
     PropagatorLabelPosition -> ComposedChar[{{19, 4.5}}]}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{6, 7.5}}]}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{8.5, 15.5}}]}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorLabelPosition -> ComposedChar[{{11, 12.5}}]}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][3] -> {20, 10}, 
    Vertex[3][4] -> {7, 3}, Vertex[1][4] -> {20, 3}, 
    Vertex[1][2] -> {20, 17}, Vertex[3][2] -> {15, 17}, 
    Vertex[3][3] -> {15, 7}, Vertex[3][1] -> {3, 12}, 
    Vertex[3][-1] -> {7, 10}, Vertex[3][-2] -> {12, 10}}, {}}
 
GraphPoints[_Topology] := $Undefined
 
