GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Incoming][Vertex[1][2], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[4][4]], 
    Propagator[Loop[2]][Vertex[4][3], Vertex[4][4]], 
    Propagator[Loop[3]][Vertex[4][3], Vertex[4][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[4][2] -> {7, 10}, Vertex[4][3] -> {13, 13}, 
    Vertex[4][4] -> {13, 7}, Vertex[1][3] -> {20, 13}, 
    Vertex[1][4] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[2]][Vertex[4][3], Vertex[4][4]], 
    Propagator[Loop[3]][Vertex[4][3], Vertex[4][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[3][1] -> {7, 13}, Vertex[3][2] -> {7, 7}, 
    Vertex[4][3] -> {13, 13}, Vertex[4][4] -> {13, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[4][3], Vertex[4][4]], 
    Propagator[Loop[3]][Vertex[4][3], Vertex[4][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[3][1] -> {7, 13}, Vertex[3][2] -> {7, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[4][3] -> {13, 7}, Vertex[4][4] -> {13, 13}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][3]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][4]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[3]][Vertex[4][3], Vertex[4][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[3][1] -> {7, 13}, Vertex[3][2] -> {7, 7}, 
    Vertex[4][3] -> {13, 13}, Vertex[4][4] -> {13, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][4]], 
    Propagator[Loop[2]][Vertex[4][2], Vertex[4][4]], 
    Propagator[Loop[3]][Vertex[4][2], Vertex[4][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 2}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[3][1] -> {5, 13}, Vertex[3][3] -> {5, 7}, 
    Vertex[4][2] -> {10, 10}, Vertex[4][4] -> {15, 13}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[4][2], Vertex[4][3]], 
    Propagator[Loop[3]][Vertex[4][2], Vertex[4][3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 2}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[3][1] -> {5, 13}, Vertex[3][4] -> {5, 7}, 
    Vertex[4][2] -> {10, 10}, Vertex[4][3] -> {15, 13}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[4][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][1]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][1]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][4]], 
    Propagator[Loop[2]][Vertex[4][1], Vertex[4][4]], 
    Propagator[Loop[3]][Vertex[4][1], Vertex[4][4]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -2}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[3][2] -> {5, 7}, Vertex[3][3] -> {5, 13}, 
    Vertex[4][1] -> {10, 10}, Vertex[4][4] -> {15, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][3]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][4]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][1]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[4][1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[4][1], Vertex[4][2]], 
    Propagator[Loop[3]][Vertex[4][1], Vertex[4][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[3][3] -> {5, 13}, Vertex[4][1] -> {7, 10}, 
    Vertex[4][2] -> {13, 10}, Vertex[3][4] -> {15, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[4][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][1]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][1]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][3]], 
    Propagator[Loop[2]][Vertex[4][1], Vertex[4][3]], 
    Propagator[Loop[3]][Vertex[4][1], Vertex[4][3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -2}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[3][4] -> {5, 13}, Vertex[3][2] -> {5, 7}, 
    Vertex[4][1] -> {8, 10}, Vertex[4][3] -> {13, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][4]], 
    Propagator[Incoming][Vertex[1][2], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][3], Vertex[3][3]], 
    Propagator[Outgoing][Vertex[1][4], Vertex[3][4]], 
    Propagator[Internal][Vertex[3][3], Vertex[4][2]], 
    Propagator[Internal][Vertex[3][4], Vertex[4][1]], 
    Propagator[Loop[1]][Vertex[4][1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[4][1], Vertex[4][2]], 
    Propagator[Loop[3]][Vertex[4][1], Vertex[4][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 13}, Vertex[1][2] -> {0, 7}, 
    Vertex[1][3] -> {20, 13}, Vertex[1][4] -> {20, 7}, 
    Vertex[4][1] -> {7, 10}, Vertex[4][2] -> {13, 10}, 
    Vertex[3][3] -> {15, 7}, Vertex[3][4] -> {10, 15}}, {}}
 
GraphPoints[_Topology] := $Undefined
