GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[5][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[5][2]], 
    Propagator[Loop[1]][Vertex[5][1], Vertex[5][2]], 
    Propagator[Loop[2]][Vertex[5][1], Vertex[5][2]], 
    Propagator[Loop[3]][Vertex[5][1], Vertex[5][2]], 
    Propagator[Loop[4]][Vertex[5][1], Vertex[5][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[5][1] -> {7, 10}, 
    Vertex[5][2] -> {13, 10}, Vertex[1][2] -> {20, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[4][2], Vertex[5][-2]], 
    Propagator[Loop[2]][Vertex[4][2], Vertex[5][-2]], 
    Propagator[Loop[3]][Vertex[4][2], Vertex[5][-2]], 
    Propagator[Loop[4]][Vertex[3][1], Vertex[5][-2]], 
    Propagator[Loop[4]][Vertex[3][1], Vertex[5][-2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[5][-2] -> {10, 10}, Vertex[4][2] -> {15, 10}, 
    Vertex[1][2] -> {20, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[5][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[5][2]], 
    Propagator[Loop[2]][Vertex[4][-1], Vertex[5][2]], 
    Propagator[Loop[3]][Vertex[4][-1], Vertex[5][2]], 
    Propagator[Loop[4]][Vertex[4][-1], Vertex[5][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][-1] -> {13, 13}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[5][2] -> {13, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[4][1], Vertex[5][-2]], 
    Propagator[Loop[2]][Vertex[4][1], Vertex[5][-2]], 
    Propagator[Loop[3]][Vertex[4][1], Vertex[5][-2]], 
    Propagator[Loop[4]][Vertex[3][2], Vertex[5][-2]], 
    Propagator[Loop[4]][Vertex[3][2], Vertex[5][-2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][1] -> {5, 10}, 
    Vertex[5][-2] -> {10, 10}, Vertex[3][2] -> {15, 10}, 
    Vertex[1][2] -> {20, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[4][-2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[4][-1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[4][-2], Vertex[4][-1]], 
    Propagator[Loop[3]][Vertex[4][-2], Vertex[4][-1]], 
    Propagator[Loop[4]][Vertex[4][-2], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[4][2] -> {10, 5}, Vertex[4][-2] -> {7, 13}, 
    Vertex[4][-1] -> {13, 13}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[5][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[5][1]], 
    Propagator[Loop[2]][Vertex[4][-1], Vertex[5][1]], 
    Propagator[Loop[3]][Vertex[4][-1], Vertex[5][1]], 
    Propagator[Loop[4]][Vertex[4][-1], Vertex[5][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][-1] -> {13, 7}, 
    Vertex[1][2] -> {20, 10}, Vertex[5][1] -> {7, 7}, 
    Vertex[3][2] -> {10, 13}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[5][-2]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[5][-2]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[5][-2]], 
    Propagator[Loop[4]][Vertex[3][2], Vertex[5][-2]], 
    Propagator[Loop[4]][Vertex[3][2], Vertex[5][-2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1.5}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1.5}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][2] -> {15, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[3][-1] -> {5, 15}, Vertex[5][-2] -> {10, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[5][-2]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[5][-2]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[5][-2]], 
    Propagator[Loop[4]][Vertex[3][1], Vertex[5][-2]], 
    Propagator[Loop[4]][Vertex[3][1], Vertex[5][-2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[5][-2] -> {10, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[3][2] -> {15, 6}, Vertex[3][-1] -> {15, 14}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[5][-2]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[5][-2]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[5][-2]], 
    Propagator[Loop[4]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[4]][Vertex[3][1], Vertex[5][-2]], 
    Propagator[Loop[4]][Vertex[3][2], Vertex[5][-2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][2] -> {10, 13}, Vertex[5][-2] -> {10, 7}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][-1] -> {15, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-2]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[4][-2], Vertex[4][-1]], 
    Propagator[Loop[3]][Vertex[4][-2], Vertex[4][-1]], 
    Propagator[Loop[4]][Vertex[4][-2], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 2}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][2] -> {15, 10}, 
    Vertex[4][-2] -> {7, 7}, Vertex[4][-1] -> {13, 7}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[4][-2]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[4][-1]], 
    Propagator[Loop[3]][Vertex[4][-2], Vertex[4][-1]], 
    Propagator[Loop[4]][Vertex[4][-2], Vertex[4][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[4][-2] -> {10, 13}, Vertex[4][-1] -> {10, 7}, 
    Vertex[3][2] -> {15, 10}, Vertex[1][2] -> {20, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][-1]], 
    Propagator[Loop[2]][Vertex[4][-2], Vertex[4][-1]], 
    Propagator[Loop[3]][Vertex[4][-2], Vertex[4][-1]], 
    Propagator[Loop[4]][Vertex[3][2], Vertex[4][-2]], 
    Propagator[Loop[4]][Vertex[3][2], Vertex[4][-2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {4, 10}, 
    Vertex[4][-1] -> {8, 10}, Vertex[4][-2] -> {12, 10}, 
    Vertex[3][2] -> {16, 10}, Vertex[1][2] -> {20, 10}}, {}}
 
GraphPoints[_Topology] := $Undefined
