GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[4][1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[4][-3], Vertex[4][1]], 
    Propagator[Loop[3]][Vertex[4][-3], Vertex[4][2]], 
    Propagator[Loop[4]][Vertex[4][-3], Vertex[4][2]], 
    Propagator[Loop[5]][Vertex[4][-3], Vertex[4][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1.4}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1.4}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1.4}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1.4}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[4][1] -> {5, 10}, Vertex[4][2] -> {15, 10}, 
    Vertex[4][-3] -> {10, 15}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[4][1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[4][-3], Vertex[4][2]], 
    Propagator[Loop[3]][Vertex[4][-3], Vertex[4][2]], 
    Propagator[Loop[4]][Vertex[4][-3], Vertex[4][1]], 
    Propagator[Loop[5]][Vertex[4][-3], Vertex[4][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[4][1] -> {5, 10}, Vertex[4][2] -> {15, 10}, 
    Vertex[4][-3] -> {10, 15}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[5][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[4][1]], 
    Propagator[Loop[2]][Vertex[4][1], Vertex[5][2]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[5][2]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[5][2]], 
    Propagator[Loop[5]][Vertex[4][1], Vertex[5][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[4][1] -> {5, 6}, Vertex[3][-1] -> {5, 14}, 
    Vertex[5][2] -> {10, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[5][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[4][2], Vertex[5][1]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[5][1]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[5][1]], 
    Propagator[Loop[5]][Vertex[4][2], Vertex[5][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1.5}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1.5}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1.5}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1.5}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[5][1] -> {5, 10}, Vertex[3][-1] -> {12, 15}, 
    Vertex[4][2] -> {12, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[4][-3], Vertex[4][2]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[5]][Vertex[4][-3], Vertex[4][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[4][2] -> {10, 5}, 
    Vertex[3][-1] -> {10, 15}, Vertex[4][-3] -> {10, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][1], Vertex[4][-3]], 
    Propagator[Loop[3]][Vertex[4][-3], Vertex[4][2]], 
    Propagator[Loop[4]][Vertex[4][-3], Vertex[4][2]], 
    Propagator[Loop[5]][Vertex[3][-1], Vertex[4][-3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[4][-3] -> {10, 7}, Vertex[4][2] -> {15, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][-1] -> {10, 15}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[3][1], Vertex[4][-3]], 
    Propagator[Loop[2]][Vertex[3][1], Vertex[4][2]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[5]][Vertex[4][-3], Vertex[4][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[4][-3] -> {10, 13}, Vertex[3][-1] -> {15, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[4][2] -> {10, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[5][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][1], Vertex[5][2]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[5][2]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[5][2]], 
    Propagator[Loop[5]][Vertex[3][-2], Vertex[5][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][-2] -> {10, 15}, 
    Vertex[5][2] -> {10, 5}, Vertex[3][-1] -> {10, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[5][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[5][2]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[5][2]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[5][2]], 
    Propagator[Loop[5]][Vertex[3][-2], Vertex[5][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][-2] -> {12, 15}, 
    Vertex[5][2] -> {12, 10}, Vertex[3][-1] -> {12, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][2], Vertex[4][1]], 
    Propagator[Loop[2]][Vertex[4][-3], Vertex[4][1]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[5]][Vertex[4][-3], Vertex[4][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][1] -> {5, 10}, 
    Vertex[3][2] -> {10, 13}, Vertex[4][-3] -> {10, 7}, 
    Vertex[3][-1] -> {15, 10}, Vertex[1][2] -> {20, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[4][1]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[4][-3]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[4][1]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[5]][Vertex[4][-3], Vertex[4][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 0.9}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -0.9}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[4][1] -> {5, 10}, Vertex[3][2] -> {15, 10}, 
    Vertex[3][-1] -> {5, 15}, Vertex[4][-3] -> {10, 13}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[4][1]], 
    Propagator[Loop[2]][Vertex[4][-3], Vertex[4][1]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[3]][Vertex[3][2], Vertex[4][-3]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[5]][Vertex[4][-3], Vertex[4][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1.3}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 0.8}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1.3}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][1] -> {5, 10}, 
    Vertex[3][-1] -> {10, 13}, Vertex[4][-3] -> {10, 7}, 
    Vertex[3][2] -> {15, 10}, Vertex[1][2] -> {20, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[5][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[5][1]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[5][1]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[5][1]], 
    Propagator[Loop[5]][Vertex[3][-2], Vertex[5][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 0.4}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, 
     PropagatorDLabelPosition -> {Automatic, Automatic}, 
     PropagatorHeight -> 1}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[5][1] -> {5, 10}, Vertex[3][-1] -> {13, 10}, 
    Vertex[3][-2] -> {15, 15}, Vertex[3][2] -> {15, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[5][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[5][1]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[5][1]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[5][1]], 
    Propagator[Loop[5]][Vertex[3][-2], Vertex[5][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[5][1] -> {5, 10}, 
    Vertex[3][2] -> {15, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[3][-2] -> {10, 14}, Vertex[3][-1] -> {10, 6}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[4][-3]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[5]][Vertex[3][-2], Vertex[4][-3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][-1] -> {15, 13}, Vertex[1][2] -> {20, 10}, 
    Vertex[3][-2] -> {10, 15}, Vertex[3][2] -> {10, 5}, 
    Vertex[4][-3] -> {10, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][1], Vertex[4][-3]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[3]][Vertex[3][2], Vertex[4][-3]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[5]][Vertex[3][-2], Vertex[4][-3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 0.5}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][2] -> {15, 10}, 
    Vertex[4][-3] -> {10, 6}, Vertex[3][-2] -> {8., 13.}, 
    Vertex[3][-1] -> {12, 13}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][1], Vertex[4][-3]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[5]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[5]][Vertex[3][2], Vertex[4][-3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[4][-3] -> {10, 5}, Vertex[3][-2] -> {10, 15}, 
    Vertex[3][2] -> {16, 10}, Vertex[3][1] -> {4, 10}, 
    Vertex[3][-1] -> {10, 12}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][1], Vertex[4][-3]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[5]][Vertex[3][-2], Vertex[4][-3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 0.9}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -0.9}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][2] -> {10, 15}, 
    Vertex[4][-3] -> {8, 7}, Vertex[3][-1] -> {12, 7}, 
    Vertex[3][-2] -> {10, 12}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][2], Vertex[4][-3]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[5]][Vertex[3][-2], Vertex[4][-3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][-2] -> {10, 13}, Vertex[1][2] -> {20, 10}, 
    Vertex[3][-1] -> {7, 7}, Vertex[4][-3] -> {12, 7}, 
    Vertex[3][2] -> {15, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[4][-3]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[5]][Vertex[3][-2], Vertex[4][-3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[3][2] -> {15, 9}, Vertex[3][1] -> {5, 9}, 
    Vertex[3][-2] -> {5, 14}, Vertex[4][-3] -> {10, 14}, 
    Vertex[3][-1] -> {15, 14}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][1], Vertex[4][-3]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][-3]], 
    Propagator[Loop[5]][Vertex[3][-2], Vertex[4][-3]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[4][-3] -> {8, 7}, 
    Vertex[3][-2] -> {8, 13}, Vertex[3][2] -> {15, 13}, 
    Vertex[3][-1] -> {15, 7}}, {}}
 
GraphPoints[_Topology] := $Undefined;
