GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[4][2]], 
    Propagator[Loop[3]][Vertex[4][1], Vertex[4][2]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][1]], 
    Propagator[Loop[5]][Vertex[3][-1], Vertex[4][1]], 
    Propagator[Loop[6]][Vertex[3][-2], Vertex[4][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[3][-1] -> {6, 15}, Vertex[3][-2] -> {14, 15}, 
    Vertex[4][1] -> {6, 10}, Vertex[4][2] -> {14, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[4][1]], 
    Propagator[Loop[4]][Vertex[4][1], Vertex[4][2]], 
    Propagator[Loop[5]][Vertex[4][1], Vertex[4][2]], 
    Propagator[Loop[6]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][1] -> {5, 10}, 
    Vertex[3][-2] -> {10, 13}, Vertex[4][2] -> {10, 7}, 
    Vertex[3][-1] -> {15, 10}, Vertex[1][2] -> {20, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[4][2]], 
    Propagator[Loop[4]][Vertex[3][-2], Vertex[4][1]], 
    Propagator[Loop[5]][Vertex[3][-1], Vertex[4][1]], 
    Propagator[Loop[6]][Vertex[4][1], Vertex[4][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[4][1] -> {5, 10}, Vertex[4][2] -> {15, 10}, 
    Vertex[3][-1] -> {10, 12}, Vertex[3][-2] -> {10, 15}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[4][2]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[4][1]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][1]], 
    Propagator[Loop[5]][Vertex[3][-1], Vertex[4][1]], 
    Propagator[Loop[6]][Vertex[3][-2], Vertex[4][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][1] -> {5, 10}, 
    Vertex[3][-2] -> {10, 13}, Vertex[3][-1] -> {10, 7}, 
    Vertex[4][2] -> {15, 10}, Vertex[1][2] -> {20, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-3], Vertex[3][-2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][2]], 
    Propagator[Loop[4]][Vertex[3][-3], Vertex[4][2]], 
    Propagator[Loop[5]][Vertex[3][-3], Vertex[4][2]], 
    Propagator[Loop[6]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[3][-2] -> {10, 13}, Vertex[3][-1] -> {10, 7}, 
    Vertex[3][-3] -> {15, 13}, Vertex[4][2] -> {15, 7}, 
    Vertex[1][2] -> {20, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-3], Vertex[3][-2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][1], Vertex[4][2]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][2]], 
    Propagator[Loop[4]][Vertex[3][-3], Vertex[3][-1]], 
    Propagator[Loop[5]][Vertex[3][-3], Vertex[3][-1]], 
    Propagator[Loop[6]][Vertex[3][-2], Vertex[4][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][-2] -> {10, 15}, 
    Vertex[3][-3] -> {15, 15}, Vertex[3][-1] -> {15, 10}, 
    Vertex[4][2] -> {10, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-3], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-3], Vertex[3][-1]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][2]], 
    Propagator[Loop[5]][Vertex[3][-2], Vertex[4][2]], 
    Propagator[Loop[6]][Vertex[3][-3], Vertex[4][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][-2] -> {10, 5}, 
    Vertex[3][-3] -> {10, 15}, Vertex[4][2] -> {15, 10}, 
    Vertex[3][-1] -> {10, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-3], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][2]], 
    Propagator[Loop[4]][Vertex[3][-3], Vertex[4][2]], 
    Propagator[Loop[5]][Vertex[3][-3], Vertex[4][2]], 
    Propagator[Loop[6]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[3][-2] -> {7, 6}, Vertex[4][2] -> {13, 14}, 
    Vertex[3][-1] -> {13, 6}, Vertex[3][-3] -> {7, 14}, 
    Vertex[3][1] -> {7, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-3], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[4][2]], 
    Propagator[Loop[3]][Vertex[3][-3], Vertex[3][-2]], 
    Propagator[Loop[4]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[5]][Vertex[3][-1], Vertex[4][2]], 
    Propagator[Loop[6]][Vertex[3][-3], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][-3] -> {10, 15}, 
    Vertex[4][2] -> {10, 5}, Vertex[3][-2] -> {10, 10}, 
    Vertex[3][-1] -> {15, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-3], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[4][2]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[4]][Vertex[3][-3], Vertex[3][-1]], 
    Propagator[Loop[5]][Vertex[3][-3], Vertex[3][-1]], 
    Propagator[Loop[6]][Vertex[3][-2], Vertex[4][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][-3] -> {5, 14}, 
    Vertex[4][2] -> {13, 10}, Vertex[3][-2] -> {13, 14}, 
    Vertex[3][-1] -> {9, 14}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-3], Vertex[3][-2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-3], Vertex[3][-1]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][1]], 
    Propagator[Loop[5]][Vertex[3][-2], Vertex[4][1]], 
    Propagator[Loop[6]][Vertex[3][-3], Vertex[3][2]], 
    Propagator[Loop[6]][Vertex[3][2], Vertex[4][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][1] -> {5, 10}, 
    Vertex[3][-2] -> {10, 15}, Vertex[3][-1] -> {10, 10}, 
    Vertex[3][2] -> {10, 5}, Vertex[3][-3] -> {15, 10}, 
    Vertex[1][2] -> {20, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-3], Vertex[3][-2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[3]][Vertex[3][2], Vertex[4][1]], 
    Propagator[Loop[4]][Vertex[3][-3], Vertex[4][1]], 
    Propagator[Loop[5]][Vertex[3][-3], Vertex[4][1]], 
    Propagator[Loop[6]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 0.3}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[3][-1] -> {14, 11}, Vertex[3][-2] -> {14, 15}, 
    Vertex[4][1] -> {6, 11}, Vertex[3][-3] -> {6, 15}, 
    Vertex[3][2] -> {10, 9}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-3], Vertex[3][-2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][1]], 
    Propagator[Loop[4]][Vertex[3][-3], Vertex[3][2]], 
    Propagator[Loop[4]][Vertex[3][2], Vertex[4][1]], 
    Propagator[Loop[5]][Vertex[3][-3], Vertex[4][1]], 
    Propagator[Loop[6]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[4][1] -> {5, 5}, Vertex[3][2] -> {15, 5}, 
    Vertex[3][-1] -> {6, 13}, Vertex[3][-2] -> {11, 13}, 
    Vertex[3][-3] -> {13, 9}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-3], Vertex[3][-2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][1]], 
    Propagator[Loop[4]][Vertex[3][-3], Vertex[4][1]], 
    Propagator[Loop[5]][Vertex[3][-3], Vertex[4][1]], 
    Propagator[Loop[6]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][1] -> {5, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][2] -> {15, 10}, 
    Vertex[3][-2] -> {12, 12}, Vertex[3][-1] -> {10, 8}, 
    Vertex[3][-3] -> {8, 15}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-3], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-3], Vertex[3][-1]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[4][1]], 
    Propagator[Loop[5]][Vertex[3][-2], Vertex[4][1]], 
    Propagator[Loop[6]][Vertex[3][-3], Vertex[4][1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][1] -> {5, 10}, 
    Vertex[3][-3] -> {10, 15}, Vertex[3][2] -> {15, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][-1] -> {10, 10}, 
    Vertex[3][-2] -> {10, 5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-3], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[3]][Vertex[3][-1], Vertex[4][1]], 
    Propagator[Loop[4]][Vertex[3][-3], Vertex[4][1]], 
    Propagator[Loop[5]][Vertex[3][-3], Vertex[4][1]], 
    Propagator[Loop[6]][Vertex[3][-2], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][1] -> {5, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][-1] -> {11, 5}, 
    Vertex[3][-2] -> {14, 9}, Vertex[3][-3] -> {9, 13}, 
    Vertex[3][2] -> {11.5, 11}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-4], Vertex[3][-3]], 
    Propagator[Loop[2]][Vertex[3][-3], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[4][2]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[4]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[5]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[6]][Vertex[3][-3], Vertex[3][-2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[4][2] -> {10, 5}, Vertex[3][-2] -> {13, 10}, 
    Vertex[3][-3] -> {7, 10}, Vertex[3][-4] -> {7, 14}, 
    Vertex[3][-1] -> {13, 14}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-4], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-3], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[3][-3], Vertex[3][-2]], 
    Propagator[Loop[3]][Vertex[3][-4], Vertex[3][-2]], 
    Propagator[Loop[4]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[5]][Vertex[3][-3], Vertex[3][-1]], 
    Propagator[Loop[6]][Vertex[3][-4], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[4][2] -> {5, 10}, 
    Vertex[3][-4] -> {10, 13}, Vertex[3][-3] -> {10, 7}, 
    Vertex[3][-2] -> {15, 13}, Vertex[3][-1] -> {15, 7}, 
    Vertex[1][2] -> {20, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[4][2]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-4], Vertex[4][2]], 
    Propagator[Loop[1]][Vertex[3][-3], Vertex[4][2]], 
    Propagator[Loop[2]][Vertex[3][-3], Vertex[3][-2]], 
    Propagator[Loop[3]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[4]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[5]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[6]][Vertex[3][-3], Vertex[3][-2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[4][2] -> {10, 5}, Vertex[3][-4] -> {5, 11}, 
    Vertex[3][-3] -> {15, 11}, Vertex[3][-2] -> {12, 15}, 
    Vertex[3][-1] -> {8, 15}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[2]][Vertex[3][-3], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[3]][Vertex[3][-4], Vertex[3][-3]], 
    Propagator[Loop[4]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[5]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[6]][Vertex[3][-3], Vertex[3][2]], 
    Propagator[Loop[6]][Vertex[3][-2], Vertex[3][2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> 1}, 
    {PropagatorEndpoints -> Vertex, PropagatorHeight -> -1}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[3][2] -> {16, 10}, Vertex[3][1] -> {4, 10}, 
    Vertex[3][-2] -> {10, 5}, Vertex[3][-4] -> {10, 12}, 
    Vertex[3][-3] -> {10, 15}, Vertex[3][-1] -> {10, 8}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[2]][Vertex[3][-3], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[3]][Vertex[3][-4], Vertex[3][-3]], 
    Propagator[Loop[4]][Vertex[3][-4], Vertex[3][2]], 
    Propagator[Loop[4]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[5]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[6]][Vertex[3][-3], Vertex[3][-2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {4, 10}, 
    Vertex[3][-3] -> {8, 13}, Vertex[3][-2] -> {8, 7}, 
    Vertex[3][-4] -> {12, 13}, Vertex[3][-1] -> {12, 7}, 
    Vertex[3][2] -> {16, 10}, Vertex[1][2] -> {20, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][-1]], 
    Propagator[Loop[2]][Vertex[3][-3], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[3]][Vertex[3][-4], Vertex[3][-3]], 
    Propagator[Loop[4]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[5]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[6]][Vertex[3][-3], Vertex[3][-2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[3][1] -> {5, 5}, Vertex[3][2] -> {15, 5}, 
    Vertex[3][-3] -> {5, 9}, Vertex[3][-1] -> {12, 13}, 
    Vertex[3][-2] -> {15, 9}, Vertex[3][-4] -> {8, 13}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-3], Vertex[3][-2]], 
    Propagator[Loop[3]][Vertex[3][-4], Vertex[3][2]], 
    Propagator[Loop[3]][Vertex[3][-3], Vertex[3][2]], 
    Propagator[Loop[4]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[5]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[6]][Vertex[3][-3], Vertex[3][-2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {4, 10}, 
    Vertex[3][2] -> {16, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[3][-4] -> {13, 6}, Vertex[3][-3] -> {13, 14}, 
    Vertex[3][-2] -> {7, 14}, Vertex[3][-1] -> {7, 6}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-3], Vertex[3][-2]], 
    Propagator[Loop[3]][Vertex[3][-3], Vertex[3][-1]], 
    Propagator[Loop[4]][Vertex[3][-4], Vertex[3][2]], 
    Propagator[Loop[4]][Vertex[3][-3], Vertex[3][2]], 
    Propagator[Loop[5]][Vertex[3][-4], Vertex[3][-2]], 
    Propagator[Loop[6]][Vertex[3][-4], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[3][-1] -> {7, 5}, Vertex[3][-3] -> {13, 5}, 
    Vertex[3][-2] -> {7, 15}, Vertex[3][-4] -> {13, 15}, 
    Vertex[3][1] -> {4, 10}, Vertex[3][2] -> {16, 10}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-3], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[3]][Vertex[3][-4], Vertex[3][-3]], 
    Propagator[Loop[4]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[5]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[6]][Vertex[3][-3], Vertex[3][-2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[3][1] -> {4, 10}, Vertex[3][-3] -> {12, 5}, 
    Vertex[3][2] -> {16, 10}, Vertex[3][-2] -> {12, 15}, 
    Vertex[3][-1] -> {6, 9}, Vertex[3][-4] -> {10, 6}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-3], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[3]][Vertex[3][-3], Vertex[3][-1]], 
    Propagator[Loop[4]][Vertex[3][-4], Vertex[3][-3]], 
    Propagator[Loop[5]][Vertex[3][-4], Vertex[3][-2]], 
    Propagator[Loop[6]][Vertex[3][-4], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {5, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][-4] -> {10, 10}, 
    Vertex[3][2] -> {15, 10}, Vertex[3][-2] -> {10, 5}, 
    Vertex[3][-1] -> {7, 15}, Vertex[3][-3] -> {13, 15}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][-3], Vertex[3][-2]], 
    Propagator[Loop[3]][Vertex[3][-4], Vertex[3][-3]], 
    Propagator[Loop[4]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[5]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[6]][Vertex[3][-3], Vertex[3][-2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[1][2] -> {20, 10}, 
    Vertex[3][1] -> {5, 5}, Vertex[3][2] -> {15, 5}, 
    Vertex[3][-2] -> {5, 9}, Vertex[3][-3] -> {5, 15}, 
    Vertex[3][-4] -> {15, 15}, Vertex[3][-1] -> {15, 9}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][-3], Vertex[3][-2]], 
    Propagator[Loop[3]][Vertex[3][-3], Vertex[3][-1]], 
    Propagator[Loop[4]][Vertex[3][-4], Vertex[3][-3]], 
    Propagator[Loop[5]][Vertex[3][-4], Vertex[3][-2]], 
    Propagator[Loop[6]][Vertex[3][-4], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 5}, Vertex[3][1] -> {5, 5}, Vertex[1][2] -> {20, 5}, 
    Vertex[3][2] -> {15, 5}, Vertex[3][-4] -> {10, 13.5}, 
    Vertex[3][-2] -> {6, 11}, Vertex[3][-1] -> {14, 11}, 
    Vertex[3][-3] -> {10, 8.5}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][1]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][2]], 
    Propagator[Loop[2]][Vertex[3][-3], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[3]][Vertex[3][-4], Vertex[3][-3]], 
    Propagator[Loop[4]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[5]][Vertex[3][-4], Vertex[3][-1]], 
    Propagator[Loop[6]][Vertex[3][-3], Vertex[3][-2]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 10}, Vertex[3][1] -> {4, 10}, 
    Vertex[1][2] -> {20, 10}, Vertex[3][-2] -> {8, 5}, 
    Vertex[3][-3] -> {8, 15}, Vertex[3][2] -> {14, 5}, 
    Vertex[3][-1] -> {14, 10}, Vertex[3][-4] -> {14, 15}}, {}}
 
GraphPoints[Topology[Propagator[Incoming][Vertex[1][1], Vertex[3][2]], 
    Propagator[Outgoing][Vertex[1][2], Vertex[3][2]], 
    Propagator[Internal][Vertex[3][1], Vertex[3][2]], 
    Propagator[Loop[1]][Vertex[3][-2], Vertex[3][1]], 
    Propagator[Loop[1]][Vertex[3][-1], Vertex[3][1]], 
    Propagator[Loop[2]][Vertex[3][-3], Vertex[3][-2]], 
    Propagator[Loop[3]][Vertex[3][-3], Vertex[3][-1]], 
    Propagator[Loop[4]][Vertex[3][-4], Vertex[3][-3]], 
    Propagator[Loop[5]][Vertex[3][-4], Vertex[3][-2]], 
    Propagator[Loop[6]][Vertex[3][-4], Vertex[3][-1]]]] = 
  {{{PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> {None, Vertex}}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}, 
    {PropagatorEndpoints -> Vertex}, {PropagatorEndpoints -> Vertex}}, 
   {Vertex[1][1] -> {0, 5}, Vertex[1][2] -> {20, 5}, 
    Vertex[3][2] -> {10, 5}, Vertex[3][1] -> {10, 9}, 
    Vertex[3][-2] -> {5, 14}, Vertex[3][-1] -> {15, 14}, 
    Vertex[3][-4] -> {10, 19}, Vertex[3][-3] -> {10, 14}}, {}}
 
GraphPoints[_Topology] := $Undefined
